name: Hello world
on:
  push:
    branches:
      - main
      - developgit status
      - 'release/**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "A demo build"
